apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: gilgamesh06/backend:1.0
        envFrom:
        - secretRef:
            name: backend-secret
        ports:
        - containerPort: 8080
