apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: gilgamesh06/frontend:1.0
        ports:
        - containerPort: 80
        volumeMounts:
          - name: frontend-config
            mountPath: /usr/share/nginx/html/config.js
            subPath: config.js
      volumes:
        - name: frontend-config
          configMap:
            name: frontend-config
