apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: prod
stringData:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/note_app
  SPRING_DATASOURCE_USERNAME: "Solus"
  SPRING_DATASOURCE_PASSWORD: "123456"
